server:
  port: 8080

spring:
  jackson:
    time-zone: Asia/Seoul

  application:
    name: webflux-gateway

  data:
    mongodb:
      uri: mongodb+srv://minti:aivle202507%21@minti-cosmos.global.mongocluster.cosmos.azure.com/minti?tls=true&authMechanism=SCRAM-SHA-256&retrywrites=false&maxIdleTimeMS=120000

  r2dbc:
    url: r2dbc:postgresql://minti-postgre.postgres.database.azure.com:5432/postgres
    username: minti
    password: aivle202507!

app:
  fastapi:
    base-url: http://127.0.0.1:8000
  uploads:
    dir: ${UPLOAD_DIR:/tmp/uploads}
  cors:
    allowed-origins: http://localhost:3000

  auth:
    azure:
      tenant-id: "{YOUR_TENANT_ID}"        
      client-id: "e3d4b650-b562-4d6e-b248-cef599b6ecb1"    
      client-secret: "z4d8Q~NkQlD8q-..3Dd80CrmoeWoyOnZvdmQ9cI7" 
      redirect-uri: "http://localhost:3000/api/auth/callback"  

      token-uri: "https://a8b5b521-af3e-494c-9d73-78025baff26b.ciamlogin.com/a8b5b521-af3e-494c-9d73-78025baff26b/oauth2/v2.0/token"
      issuer:   "https://a8b5b521-af3e-494c-9d73-78025baff26b.ciamlogin.com/a8b5b521-af3e-494c-9d73-78025baff26b/v2.0"
      jwks-uri: "https://a8b5b521-af3e-494c-9d73-78025baff26b.ciamlogin.com/a8b5b521-af3e-494c-9d73-78025baff26b/discovery/v2.0/keys"

  security:
    jwt:
      issuer: "webflux-gateway"                    
      secret: "30a6c9dc4e194ebfa84aa90c926a5b7e1a4bd819c9ee4a1485ccd91011b94cb8"
      expires-minutes: 60                           