server:
  port: 8080

spring:
  jackson:
    time-zone: Asia/Seoul

  application:
    name: webflux-gateway

  data:
    mongodb:
      uri: mongodb+srv://minti:aivle202507%21@minti-cosmos.global.mongocluster.cosmos.azure.com/minti?tls=true&authMechanism=SCRAM-SHA-256&retrywrites=false&maxIdleTimeMS=120000

  r2dbc:
    url: r2dbc:postgresql://minti-postgre.postgres.database.azure.com:5432/postgres
    username: minti
    password: aivle202507!

app:
  fastapi:
    base-url: http://127.0.0.1:8000
  uploads:
    dir: ${UPLOAD_DIR:/tmp/uploads}
  cors:
    allowed-origins: http://localhost:3000