server:
  port: 8080

spring:
  profiles:
    active: local

  jackson:
    time-zone: Asia/Seoul

  application:
    name: webflux-gateway

  security:
    jwt:
      issuer: "webflux-gateway"                    
      expires-minutes: 60