server:
  port: ${SERVER_PORT:8080}

spring:
  jackson:
    time-zone: Asia/Seoul

  application:
    name: webflux-gateway

  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}

  r2dbc:
    url: ${SPRING_R2DBC_URL}
    username: ${SPRING_R2DBC_USERNAME}
    password: ${SPRING_R2DBC_PASSWORD}

app:
  fastapi:
    base-url: ${APP_FASTAPI_BASE_URL}
  uploads:
    dir: ${UPLOAD_DIR:/tmp/uploads}
  cors:
    allowed-origins: ${APP_CORS_ALLOWED_ORIGINS:}

  auth:
    azure:
      tenant-id: ${APP_AUTH_AZURE_TENANT_ID}
      client-id: ${APP_AUTH_AZURE_CLIENT_ID}
      client-secret: ${APP_AUTH_AZURE_CLIENT_SECRET}
      redirect-uri: ${APP_AUTH_AZURE_REDIRECT_URI}
      token-uri: ${APP_AUTH_AZURE_TOKEN_URI}
      issuer: ${APP_AUTH_AZURE_ISSUER}
      jwks-uri: ${APP_AUTH_AZURE_JWKS_URI}

  security:
    jwt:
      issuer: ${APP_SECURITY_JWT_ISSUER:webflux-gateway}
      secret: ${APP_SECURITY_JWT_SECRET}
      expires-minutes: ${APP_SECURITY_JWT_EXPIRES_MINUTES:60}
