apiVersion: v1
kind: Service
metadata:
  name: minti-backend-service
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-tcp-idle-timeout: "30"
spec:
  type: LoadBalancer
  selector:
    app: mintti-backend-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080